### ISSUE TITLE
Android SDK Problem

### ISSUE THREAD

**Issue by mustii82** [TomGrill/gdx-dialogs#11]
Error:Execution failed for task ':android:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 9 cannot be smaller than version 15 declared in library [de.tomgrill.gdxdialogs:gdx-dialogs-android:1.1.0] .../android/build/intermediates/exploded-aar/de.tomgrill.gdxdialogs/gdx-dialogs-android/1.1.0/AndroidManifest.xml
  	Suggestion: use tools:overrideLibrary="de.tomgrill.gdxdialogs.android" to force usage

Why does the Library on the new version need at least SDK 15?

**Comment by TomGrill** [comment]
note sure why I did change that. Maybe was for testing purpose with multidex. Cannot remember, will look into this.

**Comment by mustii82** [comment]
I made a Pull Request long time ago which had to solve the issue :)

**Comment by TomGrill** [comment]
I remember, wanted to think about whether to support such old APK Version at all. Then forgot about it. Lets support it for now. May change later
