### ISSUE TITLE
1.1 Problems

### ISSUE THREAD

**Issue by mustii82** [TomGrill/gdx-dialogs#12]
I get in logical this error  on the most time i exit a dialog: exit Monitoring 
after that every thing freeze 

with 1.0 it works fine...

**Comment by TomGrill** [comment]
Need more info, device, os, example code etc..

**Comment by mustii82** [comment]
i used the example code device is moto g 2. generation Android 5.0 its a weird error without a error log or exception just with this logcat log: exit Monitoring

**Comment by TomGrill** [comment]
Sorry cannot help then. Maybe a thread is blocking the app. You are on your own here.

**Comment by mustii82** [comment]
The same Code works perfect with 1.0
