### ISSUE TITLE
How to implement a Textfield only dialog which activates the textinput onShow?

### ISSUE THREAD

**Issue by spectre329** [TomGrill/gdx-dialogs#16]
Hi there Tom!

There's a game called Hearthstone. They have some textfields in there and they work like this:

When user clicks the textfield it doesn't open any dialog and it opens the white field with keyboard visible below:

![image](https://cloud.githubusercontent.com/assets/21193590/19787212/df2fbde4-9ca1-11e6-91a4-969002aab85a.png)

I can open this field with your Dialogs too, but only when I click on a textfield in a TextPromptDialog.

Is there any way that you could help me implementing the 'instant' textfield only dialog like on the screen?

I mean - a dialog which is not a dialog, but an EditText which just prompts this white area.

I would be grateful!

**Comment by TomGrill** [comment]
It is an Android specific textfield which does not exist on other platforms. So you have to implement it by your self if you need it.

**Comment by spectre329** [comment]
Thank you. I ended up reimplementing your EditText. I made an invisible Dialog without a builder (this one from builder cannot be invisible). Made an invisible edittext inside, no title, no description and when the Dialog shows I request focus programatically on the invisible edittext which prompts this setup above. When I fix everything I'll push it here.
