### ISSUE TITLE
DesktopGDXTextPrompt bug

### ISSUE THREAD

**Issue by bratiche** [TomGrill/gdx-dialogs#23]
There's a small bug in the text prompt for desktop. When you close the dialog it is registered as confirmed. This happens because `CLOSED_OPTION` is not considered as the return value of `showOptionDialog()`. Here's a simplified version of the **current** code:
```
int response = JOptionPane.showOptionDialog(...);
if (response == 1) {
    listener.cancel();
} else {
    listener.confirm(...);
}
// CLOSED_OPTION is not considered
```
According to the javadoc of `showOptionDialog()`:

> @return an integer indicating the option chosen by the user,
                  or <code>CLOSED_OPTION</code> if the user closed the dialog

So fixing it would be as easy as adding an `else if` branch.

**Comment by TomGrill** [comment]
Yep I agree. Will add when I find time to do. PR always welcome :)

**Comment by TomGrill** [comment]
Fixed with next version
