### ISSUE TITLE
TextPrompt length/lines changeable from java code side.

### ISSUE THREAD

**Issue by TomGrill** [TomGrill/gdx-dialogs#6]
Feature add request.

**Comment by SimplyBallistic** [comment]
Yes. I currently need this feature as the 16 char limit is too small.

**Comment by SimplyBallistic** [comment]
Also, when you are waiting for the dialog to be built on the UI Thread, use `Thread.yield()` instead of `Thread.sleep(10)` to allow the program to yield the CPU for more important things.

**Comment by TomGrill** [comment]
I took a 15 minute dive into yield() vs sleep(). From what I have read they say the sleep() is better than yield(). One reason was that yield() is just a suggestion to pause the thread, while sleep() truly pauses the thread.

**Comment by TomGrill** [comment]
1.2.1 provides a method so set maxLength for input. I close this. If you want to push the yield stuff further please open new issue and add some explanation why it is better than sleep(). Thanks man!
