### ISSUE TITLE
ProGuard rules needed for Android

### ISSUE THREAD

**Issue by ttencate** [TomGrill/gdx-dialogs#9]
It seems that ProGuard obfuscation by default will break gdx-dialogs, due to the reflection used in GDXDialogsSystem.

See the libGDX forums: http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=22698. Note that this isn't my thread, and I don't have details beyond what the OP mentions. In particular, I haven't tested the fix that I suggest there, and I'm not even sure it's syntactically valid.

It would be good to mention this in the setup instructions in the README, or even supply a ProGuard config that will automatically be pulled in (if such a thing is possible).

**Comment by TomGrill** [comment]
thanks, I will look into it. I hope this weekend.

**Comment by mustii82** [comment]
Please include the same fix as in gdx-facebook to avoid proguard issues

**Comment by TomGrill** [comment]
done
